### ISSUE TITLE
Regarding Dataset Mentioned in the paper "EvAC3D"

### ISSUE THREAD

**Issue by shreyas-sachan** [daniilidis-group/EvAC3D#1]
Hello,

I hope this message finds you well. I recently came across your research paper, "EvAC3D From Event-based Apparent Contours
to 3D Models via Continuous Visual Hulls", and found it to be quite intriguing. I am working on a project that draws inspiration from your work, and I believe that having access to the dataset you used would be invaluable for my research.

In your paper, it was mentioned that the dataset would be made available, but I couldn't find it in this repository or any provided links (project page, supplementary materials). Could you kindly guide me to where I might find the dataset or provide more information on its availability?

Thank you for your time and for your contributions to the field. I look forward to your response.

Best regards,
Shreyas Sachan
Max Planck Institute for Informatics,
Saarbruecken, Germany

**Comment by ZiyunClaudeWang** [comment]
Hi Shreyas,

Apologies for including the wrong link on the website. Now the website has been updated with the link to the event data as well as the gt meshes.

Best,
Claude
